### ISSUE TITLE
need a way to know when content identifiers can't be dereferenced

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#130]
When some commands, such as `preston sketch` or `preston grep`, fail to dereference hash identifiers, the output will suggest that the content was processed when in fact it was not. Let's try to grep on something that obviously doesn't exist:
```
$ echo "<blah> <http://purl.org/pav/hasVersion> <hash://sha256/0000000000000000000000000000000000000000000000000000000000000000>
." | preston grep
<urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> .
<urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> <http://www.w3.org/ns/prov#used> <hash://sha256/0000000000000000000000000000000000000000000000000000000000000000> <urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> .
<urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> <http://purl.org/dc/terms/description> "An activity that finds the locations of text matching the regular expression '(?:https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]' inside any encountered content (e.g., hash://sha256/... identifiers)."@en <urn:uuid:aec383b2-cf32-4871-b1cc-7de0b1cd25d9> .
```
The output suggests that the content `hash://sha256/0000...` was processed but contained no matches, when in fact the content was never processed because it couldn't be found. It's possible that the content identified by `hash://sha256/0000...` really does contain matches that should have been reported. When a hash identifier can't be dereferenced, I suggest to either
1. throw an error and stop everything
1. throw an error, output some statements indicating the dereferencing failure, and keep processing

Commands like `preston history`, `preston ls`, and `preston cat` throw dereferencing failures for hash identifiers, so I would expect others to do the same

**Comment by jhpoelen** [comment]
@mielliott I can see how the current output doesn't make sense: how can an activity use something that was not inspected, could not be resolved, or does not exist?

I like your idea 1. to crash the process and quit for now, because I can imagine the implementation.

And, idea 2. sounds more elegant. Did you have any ideas on what statements to generate to describe the non-existing or non-resolvable hash uri?

**Comment by jhpoelen** [comment]
After a first attempt to implement idea 1. (crash on grepping content that is unavailable via content id), I was able to generate:

```
$ echo "<blah> <http://purl.org/pav/hasVersion> <hash://sha256/0000000000000000000000000000000000000000000000000000000000000000>
." | preston grep
[main] ERROR bio.guoda.preston.cmd.CmdLine - unexpected exception
java.lang.RuntimeException: failed to get [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.process.TextMatcher.on(TextMatcher.java:70)
	at bio.guoda.preston.cmd.CmdGrep$1.emit(CmdGrep.java:66)
	at bio.guoda.preston.process.EmittingStreamRDF.copyOnEmit(EmittingStreamRDF.java:45)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:34)
	at bio.guoda.preston.cmd.CmdGrep.run(CmdGrep.java:71)
	at bio.guoda.preston.cmd.CmdGrep.run(CmdGrep.java:44)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:51)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:44)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:14)
	at bio.guoda.preston.process.ProcessorReadOnly.get(ProcessorReadOnly.java:33)
	at bio.guoda.preston.process.TextMatcher.on(TextMatcher.java:63)
	... 8 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:49)
	... 12 more
Caused by: java.io.IOException: failed to find content identified by [<hash://sha256/0000000000000000000000000000000000000000000000000000000000000000>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:27)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 14 more
java.lang.RuntimeException: failed to get [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.process.TextMatcher.on(TextMatcher.java:70)
	at bio.guoda.preston.cmd.CmdGrep$1.emit(CmdGrep.java:66)
	at bio.guoda.preston.process.EmittingStreamRDF.copyOnEmit(EmittingStreamRDF.java:45)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:34)
	at bio.guoda.preston.cmd.CmdGrep.run(CmdGrep.java:71)
	at bio.guoda.preston.cmd.CmdGrep.run(CmdGrep.java:44)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:51)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:44)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:14)
	at bio.guoda.preston.process.ProcessorReadOnly.get(ProcessorReadOnly.java:33)
	at bio.guoda.preston.process.TextMatcher.on(TextMatcher.java:63)
	... 8 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [hash://sha256/0000000000000000000000000000000000000000000000000000000000000000]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:49)
	... 12 more
Caused by: java.io.IOException: failed to find content identified by [<hash://sha256/0000000000000000000000000000000000000000000000000000000000000000>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:27)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 14 more
```

@mielliott curious to hear thought if you have any.
