### ISSUE TITLE
image missing from image corpus http://arctos.database.museum/media/10562312?open

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#132]
for some reason - http://arctos.database.museum/media/10562312?open is not getting captures in jekyll export.

https://jhpoelen.nl/bats/23e89b81-adf0-4b44-8175-c27911ddd8d5

(see attached screenshot)
![Screenshot from 2021-09-22 06-25-39](https://user-images.githubusercontent.com/1084872/134352272-53b0b698-c03d-42ab-a462-a288f1fc422f.png)

**Comment by jhpoelen** [comment]
Note the cached iDigBio image on the left and the (missing) source image on the right. 

Also, note that the original location did render the image as expected at:

http://arctos.database.museum/media/10562312?open -> https://web.corral.tacc.utexas.edu/CAS/20161217-02/jpg/chas_mamm_3302.7.jpg . 

![Screenshot from 2021-09-22 06-29-08](https://user-images.githubusercontent.com/1084872/134352739-1167bfdc-6431-4383-9d10-a294a4b35b5b.png)

**Comment by jhpoelen** [comment]
Was able to reproduce the issue using:

```
$ preston track "http://arctos.database.museum/media/10562312?open"
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#SoftwareAgent> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Agent> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<https://preston.guoda.bio> <http://purl.org/dc/terms/description> "Preston is a software program that finds, archives and provides access to biodiversity datasets."@en <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <http://purl.org/dc/terms/description> "A crawl event that discovers biodiversity archives."@en <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <http://www.w3.org/ns/prov#startedAtTime> "2021-09-22T14:06:00.145Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <http://www.w3.org/ns/prov#wasStartedBy> <https://preston.guoda.bio> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/dcmitype/Software> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2019. Preston: a biodiversity dataset tracker (Version 0.3.0) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543"@en <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Entity> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/dc/terms/description> "A biodiversity dataset graph archive."@en <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> .
[main] WARN bio.guoda.preston.store.Archiver - failed to dereference [<http://arctos.database.museum/media/10562312?open>]
org.apache.http.client.HttpResponseException: status code: 450, reason phrase: [<http://arctos.database.museum/media/10562312?open>]
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:83)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:53)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:57)
	at bio.guoda.preston.store.DereferencerContentAddressed.dereference(DereferencerContentAddressed.java:19)
	at bio.guoda.preston.store.DereferencerContentAddressed.dereference(DereferencerContentAddressed.java:8)
	at bio.guoda.preston.store.Archiver.handleBlankVersion(Archiver.java:49)
	at bio.guoda.preston.store.VersionProcessor.on(VersionProcessor.java:28)
	at bio.guoda.preston.process.StatementsListenerEmitterAdapter.on(StatementsListenerEmitterAdapter.java:12)
	at bio.guoda.preston.cmd.CmdUpdate.processQueue(CmdUpdate.java:61)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:124)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:77)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
<https://deeplinker.bio/.well-known/genid/e7838ba0-41c9-3f90-bceb-edaf8279997c> <http://www.w3.org/ns/prov#wasGeneratedBy> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<https://deeplinker.bio/.well-known/genid/e7838ba0-41c9-3f90-bceb-edaf8279997c> <http://www.w3.org/ns/prov#qualifiedGeneration> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <http://www.w3.org/ns/prov#generatedAtTime> "2021-09-22T14:06:01.986Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Generation> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <http://www.w3.org/ns/prov#wasInformedBy> <urn:uuid:e0813773-9721-425a-95a2-9f0154dce62b> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> <http://www.w3.org/ns/prov#used> <http://arctos.database.museum/media/10562312?open> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
<http://arctos.database.museum/media/10562312?open> <http://purl.org/pav/hasVersion> <https://deeplinker.bio/.well-known/genid/e7838ba0-41c9-3f90-bceb-edaf8279997c> <urn:uuid:fc79026a-5cf6-471b-b0dc-f4c2495e2589> .
```

**Comment by jhpoelen** [comment]
Similarly, 

```
$ curl -L -I "http://arctos.database.museum/media/10562312?open"
HTTP/1.1 450 
Set-Cookie: cfid=07a11439-41f1-4b3b-94c2-a9d265790e57;Path=/;Expires=Tue, 12-Oct-2021 15:47:31 UTC;HttpOnly
Set-Cookie: cftoken=0;Path=/;Expires=Tue, 12-Oct-2021 15:47:31 UTC;HttpOnly
Set-Cookie: cfid=94c04dfc-4be9-4664-b3df-58c8e72cf7c8;Path=/;Expires=Tue, 12-Oct-2021 15:47:31 UTC;HttpOnly
Set-Cookie: cftoken=0;Path=/;Expires=Tue, 12-Oct-2021 15:47:31 UTC;HttpOnly
Set-Cookie: JSESSIONID=8F32EB00537A1924C4F5806180E4C98A; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Content-Length: 616
Date: Wed, 22 Sep 2021 14:09:28 GMT
Server: lighttpd/1.4.55
```

**Comment by jhpoelen** [comment]
Root cause of this issue has been resolved by @dustymc by adding some previously blocked ip addresses to a whitelist.

**Comment by jhpoelen** [comment]
Thanks again @dustymc !
