### ISSUE TITLE
remote without trailing slash [--remote https://deeplinker.bio] causes unexpected exception

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#141]
When running:

```
$ preston history --remote https://deeplinker.bio
```

failed with 

```
> <hash://sha256/000cd23a8494a8a18f8b552e7f113af418eb2ae85e9908f61f44c720ce70608b> .
[main] ERROR bio.guoda.preston.cmd.CmdLine - unexpected exception
java.lang.RuntimeException: Failed to get version history.
	at bio.guoda.preston.cmd.CmdHistory.run(CmdHistory.java:39)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
Caused by: java.io.IOException: failed to retrieve [<hash://sha256/7d89d64a8ced42817af5c20a0c51f68338c2c1a390c7251e4e6884f768835fbe>]
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:58)
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:13)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:31)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:8)
	at bio.guoda.preston.store.HexaStoreImpl.get(HexaStoreImpl.java:44)
	at bio.guoda.preston.store.VersionUtil.findPreviousVersion(VersionUtil.java:49)
	at bio.guoda.preston.store.VersionUtil.findMostRecentVersion(VersionUtil.java:33)
	at bio.guoda.preston.cmd.CmdHistory.run(CmdHistory.java:31)
	... 3 more
Caused by: java.net.UnknownHostException: deeplinker.bio7d89d64a8ced42817af5c20a0c51f68338c2c1a390c7251e4e6884f768835fbe
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:81)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:67)
	at bio.guoda.preston.ResourcesHTTP.asInputStreamIgnore404(ResourcesHTTP.java:50)
	at bio.guoda.preston.cmd.Persisting.lambda$getDerefStreamHTTP$4(Persisting.java:180)
	at bio.guoda.preston.store.KeyValueStoreWithDereferencing.get(KeyValueStoreWithDereferencing.java:23)
	at bio.guoda.preston.store.KeyValueStoreWithDereferencing.get(KeyValueStoreWithDereferencing.java:10)
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:42)
	... 10 more
java.lang.RuntimeException: Failed to get version history.
	at bio.guoda.preston.cmd.CmdHistory.run(CmdHistory.java:39)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
Caused by: java.io.IOException: failed to retrieve [<hash://sha256/7d89d64a8ced42817af5c20a0c51f68338c2c1a390c7251e4e6884f768835fbe>]
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:58)
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:13)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:31)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:8)
	at bio.guoda.preston.store.HexaStoreImpl.get(HexaStoreImpl.java:44)
	at bio.guoda.preston.store.VersionUtil.findPreviousVersion(VersionUtil.java:49)
	at bio.guoda.preston.store.VersionUtil.findMostRecentVersion(VersionUtil.java:33)
	at bio.guoda.preston.cmd.CmdHistory.run(CmdHistory.java:31)
	... 3 more
Caused by: java.net.UnknownHostException: deeplinker.bio7d89d64a8ced42817af5c20a0c51f68338c2c1a390c7251e4e6884f768835fbe
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:81)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:67)
	at bio.guoda.preston.ResourcesHTTP.asInputStreamIgnore404(ResourcesHTTP.java:50)
	at bio.guoda.preston.cmd.Persisting.lambda$getDerefStreamHTTP$4(Persisting.java:180)
	at bio.guoda.preston.store.KeyValueStoreWithDereferencing.get(KeyValueStoreWithDereferencing.java:23)
	at bio.guoda.preston.store.KeyValueStoreWithDereferencing.get(KeyValueStoreWithDereferencing.java:10)
	at bio.guoda.preston.store.KeyValueStoreStickyFailover.get(KeyValueStoreStickyFailover.java:42)
	... 10 more
```

with unexpected error code:

```
$ echo $?
1
```

However, when running:

```
$ preston history --remote https://deeplinker.bio/
...
$ echo $? 
0
```

process ends with expected error code 0 (success).

Error message suggests that an invalid url is created that concatenates the ltd with the hexastore query (e.g., Caused by: java.net.UnknownHostException: deeplinker.bio7d89d64a8ced42817af5c20a0c51f68338c2c1a390c7251e4e6884f768835fbe).

Expected is that the process doesn't attempt to create url with such hostname. Instead the process should succeed when no newer version can be found in the remote repository chain.

**Comment by jhpoelen** [comment]
Root cause was a path generator for software heritage api.

After fix was applied I was able to regenerate:

```
$ preston history --remote https://deeplinker.bio
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/c253a5311a20c2fc082bf9bac87a1ec5eb6e4e51ff936e7be20c29c8e77dee55> .
...
<hash://sha256/83b4553edfc58e6389d427a08de533236e6a7eeb39b61239d225b0d4188d8c84> <http://purl.org/pav/previousVersion> <hash://sha256/49e079a0bac47ca17c0b14fa711b7742b9332ac64e1866adf13d294692720f9f> .
jorrit@lightgrey:preston$ echo $?
0
```

which shows that the process returns with "OK" results code (i.e. "0").
