### ISSUE TITLE
no provenance found when using [preston clone] and [preston cp]

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#166]
while 

```
$ preston history
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/24dc54e4c68f22f249f3aefd9be70fa4e76399776769769c287def8e383e81dc> .
<hash://sha256/b0762d5556c49dc6dc17975170dcb11941aba13561f819d86c6e3091fd7ae96b> <http://purl.org/pav/previousVersion> <hash://sha256/24dc54e4c68f22f249f3aefd9be70fa4e76399776769769c287def8e383e81dc> .
<hash://sha256/f29e2dad4e6b979b49553bddaa98ba355951af05441a4d85181b69e987e22fe8> <http://purl.org/pav/previousVersion> <hash://sha256/b0762d5556c49dc6dc17975170dcb11941aba13561f819d86c6e3091fd7ae96b> .
<hash://sha256/033209c8ec8a35b745c50d17910f0419b126905dc90a7345e566e744daf4e46f> <http://purl.org/pav/previousVersion> <hash://sha256/f29e2dad4e6b979b49553bddaa98ba355951af05441a4d85181b69e987e22fe8> .
<hash://sha256/2bd5c38ca228e5ca55da7d30d28eb1af4629fb969a57d8ca0e68d28704756638> <http://purl.org/pav/previousVersion> <hash://sha256/033209c8ec8a35b745c50d17910f0419b126905dc90a7345e566e744daf4e46f> .
```

for some reason:

```
$ preston cp -p directoryDepth0 some/path
[main] WARN bio.guoda.preston.store.VersionProcessor - failed to handle [<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> _:1c241855-25c9-3363-874c-d6ff71b02a0a .]
java.lang.IllegalArgumentException: found unsupported or invalid hash key [<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110>]
	at bio.guoda.preston.store.HashKeyUtil.validateHashKey(HashKeyUtil.java:30)
	at bio.guoda.preston.store.KeyValueStoreLocalFileSystemReadOnly.get(KeyValueStoreLocalFileSystemReadOnly.java:21)
	at bio.guoda.preston.store.KeyValueStoreLocalFileSystemReadOnly.get(KeyValueStoreLocalFileSystemReadOnly.java:11)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:29)
	at bio.guoda.preston.store.KeyValueStoreCopying.get(KeyValueStoreCopying.java:8)
	at bio.guoda.preston.store.TracerOfOrigins.trace(TracerOfOrigins.java:47)
	at bio.guoda.preston.store.ArchiverReadOnly.handleBlankVersion(ArchiverReadOnly.java:26)
	at bio.guoda.preston.store.VersionProcessor.on(VersionProcessor.java:27)
	at bio.guoda.preston.cmd.ReplayUtil.attemptReplay(ReplayUtil.java:80)
	at bio.guoda.preston.cmd.ReplayUtil.attemptReplay(ReplayUtil.java:47)
	at bio.guoda.preston.cmd.ReplayUtil.attemptReplay(ReplayUtil.java:40)
	at bio.guoda.preston.cmd.CloneUtil.clone(CloneUtil.java:37)
	at bio.guoda.preston.cmd.CmdCopyTo.copyAll(CmdCopyTo.java:125)
	at bio.guoda.preston.cmd.CmdCopyTo.run(CmdCopyTo.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:81)
	at bio.guoda.preston.Preston.main(Preston.java:70)
[main] WARN bio.guoda.preston.cmd.ReplayUtil - No provenance found. Please use/create a Preston data archive.
```

**Comment by jhpoelen** [comment]
After ensuring proper configuration of the provenance tracers, the following was produced:

```
$ preston track "https://duckduckgo.com"
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#SoftwareAgent> <urn:uuid:d0ed7058-5e1f-4fd7-88e1-20eb5dbc09f3> .
[...]
<https://duckduckgo.com> <http://purl.org/pav/hasVersion> <hash://sha256/42df5238289c7a48655e3062dd6515b78a257ab0e3b93d37c2932b8a57c1ccc6> <urn:uuid:8dc7b52b-6215-4ad2-9149-c2a589a8ec13> .
$ preston history
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/2131815696cc7896060e0d0dcdc1bb6d5013bba621b891b489bef54b463d8685> .
$ preston cp copy-data
$ cd copy-data/
$ ls
21  2a  42
$ cd ..
$ preston history --data-dir copy-data
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/2131815696cc7896060e0d0dcdc1bb6d5013bba621b891b489bef54b463d8685> .
```

**Comment by jhpoelen** [comment]
```
$ preston clone file://$PWD/../data
[file://...210ef59e06b640a3539cb5a] 100.0% of 78 bytes at 0.02 MB/s completed in < 1 minute
[file://...1b891b489bef54b463d8685] 100.0% of 3 kB at 0.51 MB/s completed in < 1 minute
[file://...3b93d37c2932b8a57c1ccc6] 100.0% of 5 kB at 1.85 MB/s completed in < 1 minute
$ preston history
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/2131815696cc7896060e0d0dcdc1bb6d5013bba621b891b489bef54b463d8685> .
```

**Comment by mielliott** [comment]
This still seems to be an issue for remote datasets. The latest version of preston fails to clone the Big-Bee dataset https://zenodo.org/record/5660088:
```
$ preston clone --remote https://archive.org/download/preston-ucsb-izc/data.zip/,https://zenodo.org/record/5557670/files,https://zenodo.org/record/5557670/files/5660088
[https://archive.org/down...210ef59e06b640a3539cb5a] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...c5fb6d7de3b353a0a165e42] 0 bytes at 0.00 MB/s completed in < 1 minute
[main] WARN bio.guoda.preston.cmd.ReplayUtil - No provenance found. Please use/create a Preston data archive.
```

**Comment by mielliott** [comment]
Ahhh I apologize, the problem is that the Zenodo dataset's readme gives the wrong command:
```
java -jar preston.jar clone --remote https://archive.org/download/preston-ucsb-izc/data.zip/,https://zenodo.org/record/5557670/files,https://zenodo.org/record/5557670/files/5660088
```

Also note that the last remote `https://zenodo.org/record/5557670/files/5660088` should be `https://zenodo.org/record/5660088/files`

More on this soon.

**Comment by mielliott** [comment]
The "no provenance found" error also crops up when listing the Internet Archive remote before the Zenodo one:
```
$ preston clone https://zenodo.org/record/5660088/files --remote https://archive.org/download/preston-ucsb-izc/data.zip/,https://zenodo.org/record/5660088/files
[https://zenodo.org/recor...210ef59e06b640a3539cb5a] 100.0% of 78 bytes at 0.01 MB/s completed in < 1 minute
[https://archive.org/down...70a5819cee00f2c2c277f36] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://zenodo.org/recor...c6042790aab8a901a3c4613] 100.0% of 78 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...b2e0b5b54cb57a8ea00b20c] 0 bytes at 0.00 MB/s completed in < 1 minute
[https://archive.org/down...6c94faeac3613b977b00680] 0 bytes at 0.00 MB/s completed in < 1 minute
[main] WARN bio.guoda.preston.cmd.ReplayUtil - No provenance found. Please use/create a Preston data archive.
```

Switching the order works:
```
$ preston clone https://zenodo.org/record/5660088/files --remote https://zenodo.org/record/5660088/files,https://archive.org/download/preston-ucsb-izc/data.zip/
[https://zenodo.org/recor...210ef59e06b640a3539cb5a] 100.0% of 78 bytes at 0.00 MB/s completed in < 1 minute
[https://zenodo.org/recor...files/preston-3e.tar.gz] 33.6% of 20 MB at 1.01 MB/s ETA: +0 minutes
```

Not sure if this is a problem with this specific Big-Bee dataset, or if it's related to the tarred-up format of the Zenodo repo vs. the untarred Internet Archive repo, or something else.

I'll update here when the second clone command completes. Maybe it just needs to download a few of the big fat tars before it runs into the same issue.

**Comment by mielliott** [comment]
Sorry for the mess. The conclusions here are:
- The clone command given in https://zenodo.org/record/5660088#.YulTXHbMLSI has an incorrect remote (heads up @jhpoelen)
- `preston clone` doesn't work for the Internet Archive dataset, probably because it relies on redirects (see #182)

Closing this thing.

**Comment by jhpoelen** [comment]
hey @mielliott suggest to re-open this issue. The remote content should be verified by default. I also noticed the issue with the internet archive in recent demo and forgot the report the issue.

**Comment by jhpoelen** [comment]
I've updated the readme for:

Cheadle Center for Biodiversity and Ecological Restoration, University of California Santa Barbara. (2021). UC Santa Barbara Invertebrate Zoology Collection (UCSB-IZC) Data Archive and Biodiversity Dataset Graph (0.2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5660088

to point to https://zenodo.org/record/5660088/files instead

More later on the internet archive stuff.

**Comment by jhpoelen** [comment]
I was able to run:

```
preston clone https://zenodo.org/record/5660088/files --remote https://archive.org/download/preston-ucsb-izc/data.zip/,https://zenodo.org/record/5660088/files
```

to clone the ucsb image database via internet archive. No more "no provenance found" messages.
