### ISSUE TITLE
suspicious DwC-A resources published via NEON Biorepositories missing materialSample.csv

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#173]
related to https://github.com/globalbioticinteractions/neon-biorepo/issues/3

when tracking NEON RSS biorepository, I found some suspicious DwC-A resources with missing materialSample.csv tables:

for instance, 

```
$ preston track https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip\
 preston dwc-stream
```

produced the following warning :

```
[main] WARN bio.guoda.preston.cmd.DwcRecordExtractor - suspicious DwC resource [hash://sha256/66b1e01105470a803dc6682a9aa5ce31ead4ef8ae51ae318247bbd647f0ce725] caused errors in processing
bio.guoda.preston.stream.ContentStreamException: failed to handle dwc records from [zip:hash://sha256/66b1e01105470a803dc6682a9aa5ce31ead4ef8ae51ae318247bbd647f0ce725!/materialSample.csv]
	at org.gbif.dwc.DwCArchiveStreamHandler.handleAssumedDwCArchive(DwCArchiveStreamHandler.java:90)
	at org.gbif.dwc.DwCArchiveStreamHandler.handle(DwCArchiveStreamHandler.java:55)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:35)
	at bio.guoda.preston.cmd.DwcRecordExtractor$MyContentStreamHandlerImpl.handle(DwcRecordExtractor.java:103)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:60)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:29)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:35)
	at bio.guoda.preston.cmd.DwcRecordExtractor$MyContentStreamHandlerImpl.handle(DwcRecordExtractor.java:103)
	at bio.guoda.preston.cmd.DwcRecordExtractor.on(DwcRecordExtractor.java:67)
	at bio.guoda.preston.cmd.CmdDwcRecordStream$1.emit(CmdDwcRecordStream.java:47)
	at bio.guoda.preston.process.EmittingStreamRDF.copyOnEmit(EmittingStreamRDF.java:57)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:46)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:52)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:81)
	at bio.guoda.preston.Preston.main(Preston.java:70)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/66b1e01105470a803dc6682a9aa5ce31ead4ef8ae51ae318247bbd647f0ce725!/materialSample.csv]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at org.gbif.dwc.DwCArchiveStreamHandler.createReader(DwCArchiveStreamHandler.java:124)
	at org.gbif.dwc.DwCArchiveStreamHandler.handleAssumedDwCArchive(DwCArchiveStreamHandler.java:84)
	... 23 more
Caused by: java.io.IOException: failed to find content identified by [<zip:hash://sha256/66b1e01105470a803dc6682a9aa5ce31ead4ef8ae51ae318247bbd647f0ce725!/materialSample.csv>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:54)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 26 more
```

suggesting that:

```
$ preston alias 
<https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip> <http://purl.org/pav/hasVersion> <hash://sha256/66b1e01105470a803dc6682a9aa5ce31ead4ef8ae51ae318247bbd647f0ce725> <urn:uuid:a85ac188-8595-4bf0-84d1-b3ee22129a3d> .
```

contains a DwC-A with meta.xml referencing materialSample.csv , but none was found in the published endpoint. 

See attached data.zip to reproduce. 

[data.zip](https://github.com/bio-guoda/preston/files/8780446/data.zip)

fyi @egbot @arbolitoloco @nfranz

**Comment by arbolitoloco** [comment]
Hi, @jhpoelen. The material sample output is a relatively new feature being tested in Symbiota via the NEON Biorepository Data Portal, and so we are aware of a few bugs related to the files generated in the DwC-A. This might be related to [this issue](https://github.com/BioKIC/NEON-Biorepository/issues/269) in our repo.

**Comment by jhpoelen** [comment]
hey @arbolitoloco - thanks for having a look and sharing the related issue! Unless you object, I'll keep this issue open until the underlying issue has been fixed to prevent similar issues from being reported again.

**Comment by jhpoelen** [comment]
The issue re: materialSample.csv appears to still happen. 

Any update?
 
```
$ preston track https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip | preston dwc-stream
[main] WARN bio.guoda.preston.cmd.DwcRecordExtractor - suspicious DwC resource [hash://sha256/6f19ab2050f7b494a4aa9ba46065f112bf3ce3c692408692d056bb534c005f4f] caused errors in processing
bio.guoda.preston.stream.ContentStreamException: failed to handle dwc records from [zip:hash://sha256/6f19ab2050f7b494a4aa9ba46065f112bf3ce3c692408692d056bb534c005f4f!/materialSample.csv]
	at org.gbif.dwc.DwCArchiveStreamHandler.streamRecords(DwCArchiveStreamHandler.java:106)
	at org.gbif.dwc.DwCArchiveStreamHandler.handleAssumedDwCArchive(DwCArchiveStreamHandler.java:82)
	at org.gbif.dwc.DwCArchiveStreamHandler.handle(DwCArchiveStreamHandler.java:55)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:35)
	at bio.guoda.preston.cmd.DwcRecordExtractor$MyContentStreamHandlerImpl.handle(DwcRecordExtractor.java:103)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:60)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:29)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:35)
	at bio.guoda.preston.cmd.DwcRecordExtractor$MyContentStreamHandlerImpl.handle(DwcRecordExtractor.java:103)
	at bio.guoda.preston.cmd.DwcRecordExtractor.on(DwcRecordExtractor.java:67)
	at bio.guoda.preston.cmd.CmdDwcRecordStream$1.emit(CmdDwcRecordStream.java:47)
	at bio.guoda.preston.process.EmittingStreamRDF.copyOnEmit(EmittingStreamRDF.java:57)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:46)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:52)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:85)
	at bio.guoda.preston.Preston.main(Preston.java:74)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/6f19ab2050f7b494a4aa9ba46065f112bf3ce3c692408692d056bb534c005f4f!/materialSample.csv]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at org.gbif.dwc.DwCArchiveStreamHandler.createReader(DwCArchiveStreamHandler.java:142)
	at org.gbif.dwc.DwCArchiveStreamHandler.streamRecords(DwCArchiveStreamHandler.java:100)
	... 24 more
Caused by: java.io.IOException: failed to find content identified by [<zip:hash://sha256/6f19ab2050f7b494a4aa9ba46065f112bf3ce3c692408692d056bb534c005f4f!/materialSample.csv>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:54)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 27 more
```

**Comment by jhpoelen** [comment]
@egbot @arbolitoloco @nfranz It still appears that NEON biorepositories are publishing DwC-A in which materialSample.csv is references in meta.xml but not included in the zip file. Please let me know what a good way is to report this issue. If you don't want to fix this, please let me know and I'll mark this issue as a "will not fix".

**Comment by jhpoelen** [comment]
It appears that the materialSample.csv referenced in the meta.xml of https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip is now produced as expected.

and no errors are reported when

```
$ preston track https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip | preston dwc-stream | wc -l
3020
```

Thanks for addressing this issue @egbot @arbolitoloco @nfranz

**Comment by jhpoelen** [comment]
note that - 

```
<https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip> <http://purl.org/pav/hasVersion> <hash://sha256/5a39c9fff4ebff9b4884bad65b8341ae6694bcc226ae1e775717a75bf4f8c93b> <urn:uuid:5f32d04e-e121-4edd-a672-db22a82f9b7b> .
```

was used to produce:

```
$ preston cat 'zip:https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip!/materialSample.csv' 
coreid,materialSampleID,sampleType,catalogNumber,sampleCondition,disposition,preservationType,preparationDetails,preparationDate,preparedBy,individualCount,sampleSize,storageLocation,remarks,recordID,concentration,concentrationMethod,dnaHybridization,dnaMeltingPoint,estimatedSize,poolDnaExtracts,purificationMethod,quality,qualityCheckDate,qualityRemarks,ratioOfAbsorbance260_230,ratioOfAbsorbance260_280,sampleDesignation,sieving,volume,weight,weightMethod
```

and
 
```
preston cat 'zip:https://biorepo.neonscience.org/portal/content/dwca/NEON-SWMC-SF_DwC-A.zip!/meta.xml' | xmllint --format -
```
resulted in:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns="http://rs.tdwg.org/dwc/text/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" metadata="eml.xml" xsi:schemaLocation="http://rs.tdwg.org/dwc/text/   http://rs.tdwg.org/dwc/text/tdwg_dwc_text.xsd">
  <core dateFormat="YYYY-MM-DD" encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>occurrences.csv</location>
    </files>
    <id index="0"/>
    <field index="1" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/ownerInstitutionCode"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/collectionID"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/otherCatalogNumbers"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/higherClassification"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/phylum"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/class"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/order"/>
    <field index="14" term="http://rs.tdwg.org/dwc/terms/family"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="16" term="http://rs.tdwg.org/dwc/terms/taxonID"/>
    <field index="17" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>
    <field index="18" term="http://rs.tdwg.org/dwc/terms/genus"/>
    <field index="19" term="http://rs.tdwg.org/dwc/terms/subgenus"/>
    <field index="20" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
    <field index="21" term="http://rs.tdwg.org/dwc/terms/verbatimTaxonRank"/>
    <field index="22" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
    <field index="23" term="http://rs.tdwg.org/dwc/terms/taxonRank"/>
    <field index="24" term="http://rs.tdwg.org/dwc/terms/identifiedBy"/>
    <field index="25" term="http://rs.tdwg.org/dwc/terms/dateIdentified"/>
    <field index="26" term="http://rs.tdwg.org/dwc/terms/identificationReferences"/>
    <field index="27" term="http://rs.tdwg.org/dwc/terms/identificationRemarks"/>
    <field index="28" term="http://rs.tdwg.org/dwc/terms/taxonRemarks"/>
    <field index="29" term="http://rs.tdwg.org/dwc/terms/identificationQualifier"/>
    <field index="30" term="http://rs.tdwg.org/dwc/terms/typeStatus"/>
    <field index="31" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
    <field index="32" term="http://rs.tdwg.org/dwc/terms/recordNumber"/>
    <field index="33" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="34" term="http://rs.tdwg.org/dwc/terms/year"/>
    <field index="35" term="http://rs.tdwg.org/dwc/terms/month"/>
    <field index="36" term="http://rs.tdwg.org/dwc/terms/day"/>
    <field index="37" term="http://rs.tdwg.org/dwc/terms/startDayOfYear"/>
    <field index="38" term="http://rs.tdwg.org/dwc/terms/endDayOfYear"/>
    <field index="39" term="http://rs.tdwg.org/dwc/terms/verbatimEventDate"/>
    <field index="40" term="http://rs.tdwg.org/dwc/terms/occurrenceRemarks"/>
    <field index="41" term="http://rs.tdwg.org/dwc/terms/habitat"/>
    <field index="42" term="http://rs.tdwg.org/dwc/terms/fieldNumber"/>
    <field index="43" term="http://rs.tdwg.org/dwc/terms/eventID"/>
    <field index="44" term="http://rs.tdwg.org/dwc/terms/informationWithheld"/>
    <field index="45" term="http://rs.tdwg.org/dwc/terms/dataGeneralizations"/>
    <field index="46" term="http://rs.tdwg.org/dwc/terms/dynamicProperties"/>
    <field index="47" term="http://rs.tdwg.org/dwc/terms/associatedOccurrences"/>
    <field index="48" term="http://rs.tdwg.org/dwc/terms/associatedSequences"/>
    <field index="49" term="http://rs.tdwg.org/dwc/terms/associatedTaxa"/>
    <field index="50" term="http://rs.tdwg.org/dwc/terms/reproductiveCondition"/>
    <field index="51" term="http://rs.tdwg.org/dwc/terms/establishmentMeans"/>
    <field index="52" term="http://rs.tdwg.org/dwc/terms/lifeStage"/>
    <field index="53" term="http://rs.tdwg.org/dwc/terms/sex"/>
    <field index="54" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
    <field index="55" term="http://rs.tdwg.org/dwc/terms/preparations"/>
    <field index="56" term="http://rs.tdwg.org/dwc/terms/locationID"/>
    <field index="57" term="http://rs.tdwg.org/dwc/terms/continent"/>
    <field index="58" term="http://rs.tdwg.org/dwc/terms/waterBody"/>
    <field index="59" term="http://rs.tdwg.org/dwc/terms/islandGroup"/>
    <field index="60" term="http://rs.tdwg.org/dwc/terms/island"/>
    <field index="61" term="http://rs.tdwg.org/dwc/terms/country"/>
    <field index="62" term="http://rs.tdwg.org/dwc/terms/stateProvince"/>
    <field index="63" term="http://rs.tdwg.org/dwc/terms/county"/>
    <field index="64" term="http://rs.tdwg.org/dwc/terms/municipality"/>
    <field index="65" term="http://rs.tdwg.org/dwc/terms/locality"/>
    <field index="66" term="http://rs.tdwg.org/dwc/terms/locationRemarks"/>
    <field index="67" term="http://rs.tdwg.org/dwc/terms/decimalLatitude"/>
    <field index="68" term="http://rs.tdwg.org/dwc/terms/decimalLongitude"/>
    <field index="69" term="http://rs.tdwg.org/dwc/terms/geodeticDatum"/>
    <field index="70" term="http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters"/>
    <field index="71" term="http://rs.tdwg.org/dwc/terms/verbatimCoordinates"/>
    <field index="72" term="http://rs.tdwg.org/dwc/terms/georeferencedBy"/>
    <field index="73" term="http://rs.tdwg.org/dwc/terms/georeferenceProtocol"/>
    <field index="74" term="http://rs.tdwg.org/dwc/terms/georeferenceSources"/>
    <field index="75" term="http://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus"/>
    <field index="76" term="http://rs.tdwg.org/dwc/terms/georeferenceRemarks"/>
    <field index="77" term="http://rs.tdwg.org/dwc/terms/minimumElevationInMeters"/>
    <field index="78" term="http://rs.tdwg.org/dwc/terms/maximumElevationInMeters"/>
    <field index="79" term="http://rs.tdwg.org/dwc/terms/minimumDepthInMeters"/>
    <field index="80" term="http://rs.tdwg.org/dwc/terms/maximumDepthInMeters"/>
    <field index="81" term="http://rs.tdwg.org/dwc/terms/verbatimDepth"/>
    <field index="82" term="http://rs.tdwg.org/dwc/terms/verbatimElevation"/>
    <field index="83" term="http://rs.tdwg.org/dwc/terms/disposition"/>
    <field index="84" term="http://purl.org/dc/terms/language"/>
    <field index="85" term="https://symbiota.org/terms/recordEnteredBy"/>
    <field index="86" term="http://purl.org/dc/terms/modified"/>
    <field index="87" term="http://purl.org/dc/elements/1.1/rights"/>
    <field index="88" term="http://purl.org/dc/terms/rightsHolder"/>
    <field index="89" term="http://purl.org/dc/terms/accessRights"/>
    <field index="90" term="https://symbiota.org/terms/recordID"/>
    <field index="91" term="http://purl.org/dc/terms/references"/>
  </core>
  <extension encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Identification">
    <files>
      <location>identifications.csv</location>
    </files>
    <coreid index="0"/>
    <field index="1" term="http://rs.tdwg.org/dwc/terms/identifiedBy"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/dateIdentified"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/identificationQualifier"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="5" term="https://symbiota.org/terms/tidInterpreted"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/genus"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/taxonRank"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/identificationReferences"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/identificationRemarks"/>
    <field index="13" term="http://portal.idigbio.org/terms/recordID"/>
    <field index="14" term="http://purl.org/dc/terms/modified"/>
  </extension>
  <extension encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/ac/terms/Multimedia">
    <files>
      <location>multimedia.csv</location>
    </files>
    <coreid index="0"/>
    <field index="1" term="http://purl.org/dc/terms/identifier"/>
    <field index="2" term="http://rs.tdwg.org/ac/terms/accessURI"/>
    <field index="3" term="http://rs.tdwg.org/ac/terms/thumbnailAccessURI"/>
    <field index="4" term="http://rs.tdwg.org/ac/terms/goodQualityAccessURI"/>
    <field index="5" term="http://purl.org/dc/terms/rights"/>
    <field index="6" term="http://ns.adobe.com/xap/1.0/rights/Owner"/>
    <field index="7" term="http://purl.org/dc/elements/1.1/creator"/>
    <field index="8" term="http://ns.adobe.com/xap/1.0/rights/UsageTerms"/>
    <field index="9" term="http://ns.adobe.com/xap/1.0/rights/WebStatement"/>
    <field index="10" term="http://rs.tdwg.org/ac/terms/caption"/>
    <field index="11" term="http://rs.tdwg.org/ac/terms/comments"/>
    <field index="12" term="http://rs.tdwg.org/ac/terms/providerManagedID"/>
    <field index="13" term="http://ns.adobe.com/xap/1.0/MetadataDate"/>
    <field index="14" term="http://purl.org/dc/terms/format"/>
    <field index="15" term="http://rs.tdwg.org/ac/terms/associatedSpecimenReference"/>
    <field index="16" term="http://purl.org/dc/terms/type"/>
    <field index="17" term="http://rs.tdwg.org/ac/terms/subtype"/>
    <field index="18" term="http://rs.tdwg.org/ac/terms/metadataLanguage"/>
  </extension>
  <extension encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://data.ggbn.org/schemas/ggbn/terms/MaterialSample">
    <files>
      <location>materialSample.csv</location>
    </files>
    <coreid index="0"/>
    <field index="1" term="http://rs.tdwg.org/dwc/terms/materialSampleID"/>
    <field index="2" term="http://data.ggbn.org/schemas/ggbn/terms/materialSampleType"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
    <field index="4" term="https://symbiota.org/terms/sampleCondition"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/disposition"/>
    <field index="6" term="http://data.ggbn.org/schemas/ggbn/terms/preservationType"/>
    <field index="7" term="http://data.ggbn.org/schemas/ggbn/terms/preparationProcess"/>
    <field index="8" term="http://data.ggbn.org/schemas/ggbn/terms/preparationDate"/>
    <field index="9" term="http://data.ggbn.org/schemas/ggbn/terms/preparedBy"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
    <field index="11" term="http://gensc.org/ns/mixs/samp_size"/>
    <field index="12" term="https://symbiota.org/terms/storageLocation"/>
    <field index="13" term="https://symbiota.org/terms/materialSampleRemarks"/>
    <field index="14" term="http://symbiota.org/terms/recordID"/>
    <field index="15" term="http://data.ggbn.org/schemas/ggbn/terms/concentration"/>
    <field index="16" term="http://data.ggbn.org/schemas/ggbn/terms/methodDeterminationConcentrationAndRatios"/>
    <field index="17" term="http://data.ggbn.org/schemas/ggbn/terms/DNADNAHybridization"/>
    <field index="18" term="http://data.ggbn.org/schemas/ggbn/terms/DNAMeltingPoint"/>
    <field index="19" term="http://gensc.org/ns/mixs/estimated_size"/>
    <field index="20" term="http://gensc.org/ns/mixs/pool_dna_extracts"/>
    <field index="21" term="http://data.ggbn.org/schemas/ggbn/terms/purificationMethod"/>
    <field index="22" term="http://data.ggbn.org/schemas/ggbn/terms/quality"/>
    <field index="23" term="http://data.ggbn.org/schemas/ggbn/terms/qualityCheckDate"/>
    <field index="24" term="http://data.ggbn.org/schemas/ggbn/terms/qualityRemarks"/>
    <field index="25" term="http://data.ggbn.org/schemas/ggbn/terms/ratioOfAbsorbance260_230"/>
    <field index="26" term="http://data.ggbn.org/schemas/ggbn/terms/ratioOfAbsorbance260_280"/>
    <field index="27" term="http://data.ggbn.org/schemas/ggbn/terms/sampleDesignation"/>
    <field index="28" term="http://gensc.org/ns/mixs/sieving"/>
    <field index="29" term="http://data.ggbn.org/schemas/ggbn/terms/volume"/>
    <field index="30" term="http://data.ggbn.org/schemas/ggbn/terms/weight"/>
    <field index="31" term="http://data.ggbn.org/schemas/ggbn/terms/methodDeterminationWeight"/>
  </extension>
</archive>
```
