### ISSUE TITLE
apparent api version conflict when tracking 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#180]
when running - 

preston track "https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%0A%20%20%3Fmethod%20%3FmethodLabel%0A%20%20%3Fperson%20%3FpersonLabel%0A%20%20%3Fwork%20%3FworkLabel%20%0A%20%20%3FpublicationDate%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fperson%20WHERE%20%7B%0A%20%20%20%20%3Fperson%20wdt%3AP463%20wd%3AQ112326635%20.%0A%20%20%7D%20%0A%7D%20AS%20%25researchers%0AWHERE%20%7B%0A%20%20INCLUDE%20%25researchers%0A%0A%20%20%3Fwork%20wdt%3AP50%20%3Fperson%20%3B%0A%20%20%20%20%20%20%20%20wdt%3AP4510%20%3Fmethod%20.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fpublication_datetime%20.%0A%20%20%20%20BIND%28xsd%3Adate%28%3Fpublication_datetime%29%20AS%20%3FpublicationDate%29%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3FpublicationDate%29%0A"

```
[main] WARN bio.guoda.preston.store.VersionProcessor - failed to handle [<https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%0A%20%20%3Fmethod%20%3FmethodLabel%0A%20%20%3Fperson%20%3FpersonLabel%0A%20%20%3Fwork%20%3FworkLabel%20%0A%20%20%3FpublicationDate%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fperson%20WHERE%20%7B%0A%20%20%20%20%3Fperson%20wdt%3AP463%20wd%3AQ112326635%20.%0A%20%20%7D%20%0A%7D%20AS%20%25researchers%0AWHERE%20%7B%0A%20%20INCLUDE%20%25researchers%0A%0A%20%20%3Fwork%20wdt%3AP50%20%3Fperson%20%3B%0A%20%20%20%20%20%20%20%20wdt%3AP4510%20%3Fmethod%20.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fpublication_datetime%20.%0A%20%20%20%20BIND%28xsd%3Adate%28%3Fpublication_datetime%29%20AS%20%3FpublicationDate%29%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3FpublicationDate%29%0A> <http://purl.org/pav/hasVersion> _:d4fcb343-17fe-33e7-8dcb-39f335527270 <urn:uuid:f06a3867-3721-4782-9350-b46112653556> .]
java.lang.NoSuchMethodError: org.apache.commons.io.input.CloseShieldInputStream.wrap(Ljava/io/InputStream;)Lorg/apache/commons/io/input/CloseShieldInputStream;
	at bio.guoda.preston.process.XMLUtil.parseDoc(XMLUtil.java:48)
	at bio.guoda.preston.process.XMLUtil.evaluateXPath(XMLUtil.java:40)
	at bio.guoda.preston.process.XMLUtil.handleXPath(XMLUtil.java:32)
	at bio.guoda.preston.process.RegistryReaderRSS.parseRssFeed(RegistryReaderRSS.java:151)
	at bio.guoda.preston.process.RegistryReaderRSS.parseRssFeed(RegistryReaderRSS.java:68)
	at bio.guoda.preston.process.RegistryReaderRSS.parse(RegistryReaderRSS.java:58)
	at bio.guoda.preston.process.RegistryReaderRSS.on(RegistryReaderRSS.java:40)
	at bio.guoda.preston.store.StatementsListenerEmitterAdapter.on(StatementsListenerEmitterAdapter.java:14)
	at bio.guoda.preston.store.StatementProcessor.emit(StatementProcessor.java:35)
	at bio.guoda.preston.store.StatementProcessor.emit(StatementProcessor.java:29)
	at bio.guoda.preston.store.Archiver.putVersion(Archiver.java:95)
	at bio.guoda.preston.store.Archiver.handleBlankVersion(Archiver.java:56)
	at bio.guoda.preston.store.VersionProcessor.on(VersionProcessor.java:27)
	at bio.guoda.preston.store.StatementsListenerEmitterAdapter.on(StatementsListenerEmitterAdapter.java:14)
	at bio.guoda.preston.cmd.CmdTrack.processQueue(CmdTrack.java:46)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:110)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:85)
	at bio.guoda.preston.Preston.main(Preston.java:74)
```

**Comment by jhpoelen** [comment]
was unable to reproduce after applying fix in https://github.com/bio-guoda/preston/commit/1574f868131f69613305b7521cc195068e290bdf
