### ISSUE TITLE
`cut:zip:hash://` style content id reported by Preston, but fails to resolve via [cat]

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#205]
after preston produces:

```
<urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> <http://www.w3.org/ns/prov#wasInformedBy> <urn:uuid:a7aaf0f3-567e-4dd7-9ec7-e24cbb33516c> <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> <http://www.w3.org/ns/prov#used> <hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197> <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> <http://purl.org/dc/terms/description> "An activity that finds the locations of text matching the regular expression 'Barbastello leucomelas' inside any encountered content (e.g., hash://sha256/... identifiers)."@en <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b576-597> <http://www.w3.org/ns/prov#value> "Barbastello leucomelas" <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3054-3075> <http://www.w3.org/ns/prov#value> "Barbastello leucomelas" <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3550-3571> <http://www.w3.org/ns/prov#value> "Barbastello leucomelas" <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
<cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735> <http://www.w3.org/ns/prov#value> "Barbastello leucomelas" <urn:uuid:a35b9dc6-98a8-49f4-9703-676cc63b39d5> .
```

resolving the referenced content via ```preston cat``` appears to fail - 

```
preston cat 'cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735'
```

yields:

```
[main] WARN bio.guoda.preston.stream.ArchiveStreamHandler - failed to process entry [treatments-xml-main/] in [hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197]
java.lang.IllegalArgumentException: [<zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/>] is not a valid cut URI
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.cutAndParseBytes(ContentStreamFactory.java:175)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:99)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:63)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:33)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:38)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:107)
	at bio.guoda.preston.stream.ContentStreamFactory.requestContentStream(ContentStreamFactory.java:62)
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:52)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:82)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:42)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:17)
	at bio.guoda.preston.cmd.ContentQueryUtil.handleContentQuery(ContentQueryUtil.java:26)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:63)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:42)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:89)
	at bio.guoda.preston.Preston.main(Preston.java:78)
java.io.IOException: problem retrieving [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.cmd.ContentQueryUtil.handleContentQuery(ContentQueryUtil.java:35)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:63)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:42)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:89)
	at bio.guoda.preston.Preston.main(Preston.java:78)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:84)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:42)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:17)
	at bio.guoda.preston.cmd.ContentQueryUtil.handleContentQuery(ContentQueryUtil.java:26)
	... 13 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:82)
	... 16 more
Caused by: java.io.IOException: failed to create inputstream
	at bio.guoda.preston.stream.ContentStreamFactory.requestContentStream(ContentStreamFactory.java:64)
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:52)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 18 more
Caused by: bio.guoda.preston.stream.ContentStreamException: failed to process entry [treatments-xml-main/] in [hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197]
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:71)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:33)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:38)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:107)
	at bio.guoda.preston.stream.ContentStreamFactory.requestContentStream(ContentStreamFactory.java:62)
	... 20 more
Caused by: java.lang.IllegalArgumentException: [<zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/>] is not a valid cut URI
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.cutAndParseBytes(ContentStreamFactory.java:175)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:99)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:63)
	... 24 more
java.lang.RuntimeException: java.io.IOException: problem retrieving [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:45)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:89)
	at bio.guoda.preston.Preston.main(Preston.java:78)
Caused by: java.io.IOException: problem retrieving [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.cmd.ContentQueryUtil.handleContentQuery(ContentQueryUtil.java:35)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:63)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:42)
	... 11 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:84)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:42)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:17)
	at bio.guoda.preston.cmd.ContentQueryUtil.handleContentQuery(ContentQueryUtil.java:26)
	... 13 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:82)
	... 16 more
Caused by: java.io.IOException: failed to create inputstream
	at bio.guoda.preston.stream.ContentStreamFactory.requestContentStream(ContentStreamFactory.java:64)
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:52)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 18 more
Caused by: bio.guoda.preston.stream.ContentStreamException: failed to process entry [treatments-xml-main/] in [hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197]
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:71)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:33)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:38)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:107)
	at bio.guoda.preston.stream.ContentStreamFactory.requestContentStream(ContentStreamFactory.java:62)
	... 20 more
Caused by: java.lang.IllegalArgumentException: [<zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/>] is not a valid cut URI
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.cutAndParseBytes(ContentStreamFactory.java:175)
	at bio.guoda.preston.stream.ContentStreamFactory$ContentStreamRequest.handle(ContentStreamFactory.java:99)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:63)
	... 24 more
```

**Comment by jhpoelen** [comment]
After fixing root cause by not processing archive entry directories, running:

```
preston cat 'cut:zip:hash://sha256/56caf9620cd58df6fb517dfb7cd01e2e81e54a41eef2f562c5eddfbd70ba6197!/treatments-xml-main/data/C3/05/87/C30587A9A562FF93FF2F350F875ED55F.xml!/b3714-3735'
```

yields expected result:

```
Barbastello leucomelas
```
