### ISSUE TITLE
preston history dependent works list that appears truncated prematurely

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#214]
in working with BRIT 2022 / https://github.com/bio-guoda/preston-brit-2022 ,

I found that:

```
preston history --anchor hash://sha256/f63892e3693f55911fb3bb564e7bb6ed78fb2d7ee34ff9aff5b5847d8d89f8c7\
 | head
```

produces output with fewer than 10 lines:

```
<hash://sha256/f63892e3693f55911fb3bb564e7bb6ed78fb2d7ee34ff9aff5b5847d8d89f8c7> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199> .
<hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697> .
```

however, when running

```
preston history --anchor hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697\
 | head 
```
produced at least 10 lines . . . 

```
<hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/709f15825e694b7eb787b9d6c5bd9fb3f0fda92c6486666fa7a98b62b401a305> .
<hash://sha256/709f15825e694b7eb787b9d6c5bd9fb3f0fda92c6486666fa7a98b62b401a305> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/bdba58a35f5ff397a11c757ae0f0db07e59c4789c4e0d86e38bcfe61fdc74ad0> .
<hash://sha256/bdba58a35f5ff397a11c757ae0f0db07e59c4789c4e0d86e38bcfe61fdc74ad0> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/f4f762d1cfcabc01ece1643a3d8a0ce2c3d8f78db8da00bc9ecd5f631da0c5cc> .
<hash://sha256/f4f762d1cfcabc01ece1643a3d8a0ce2c3d8f78db8da00bc9ecd5f631da0c5cc> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/55553cd7d0142c8f277bd7300684d6a819a914f65b351e52a257ed2c841f5919> .
<hash://sha256/55553cd7d0142c8f277bd7300684d6a819a914f65b351e52a257ed2c841f5919> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/69da436fd0f564c5a621b2ec7970b780bb497526e158114510425ea25e1e093e> .
<hash://sha256/69da436fd0f564c5a621b2ec7970b780bb497526e158114510425ea25e1e093e> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/756c032afdd13afb3c69251557180f44651a189c76fc01a867a3b8ca8204499c> .
<hash://sha256/756c032afdd13afb3c69251557180f44651a189c76fc01a867a3b8ca8204499c> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/f2f14ce415515dc5bc3def57acd6360e628f9ff437540674bb81512988483b50> .
<hash://sha256/f2f14ce415515dc5bc3def57acd6360e628f9ff437540674bb81512988483b50> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/c844e6c783ccf954748efe116d2110cae0b6b30caea79821bb31a033da1e715d> .
<hash://sha256/c844e6c783ccf954748efe116d2110cae0b6b30caea79821bb31a033da1e715d> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/59256903752d97da8f87088e8dccf8ef68123e397b6fb2e7b41b44f6bc5cd433> .
<hash://sha256/59256903752d97da8f87088e8dccf8ef68123e397b6fb2e7b41b44f6bc5cd433> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/0df0fc5aeed127f7f744169f38467b2930e83cd5a0cf15ab3412a469c5e5f787> .
```
 

expected that history of successor  (e.g., hash://sha256/f63892e3693f55911fb3bb564e7bb6ed78fb2d7ee34ff9aff5b5847d8d89f8c7) to be longer than that of one of its predecessors (e.g., .hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697) .

**Comment by jhpoelen** [comment]
similarly, 

```
preston history --anchor hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199\
 | head
```

produces:
```
<hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697> .
```

just a single line.

**Comment by jhpoelen** [comment]
In tracing the provenance of 

```
hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199
```


the following rdf parsing exception is thrown:

```
org.apache.jena.riot.RiotParseException: [line: 114, col: 1 ] Failed to find a prefix name or keyword: %c(%d;0x%04X)
```

**Comment by jhpoelen** [comment]
which corresponds L114 and surrounding lines 113 and 115:

```
preston cat 'line:hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199!/L113-L115'
```


```
<hash://sha256/80f20f05bb7161dc3451e3e16b44a29bf208a1d1d47cc8a1505a40cf9d826bed> <http://www.w3.org/ns/prov#qualifiedGeneration> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .
001/XMLSchema#dateTime> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .
<urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Generation> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .```

**Comment by jhpoelen** [comment]
Note that line L114 appears as:

```
001/XMLSchema#dateTime> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .
```

and is *not* a valid rdf line.

**Comment by jhpoelen** [comment]
After introducing https://github.com/nxparser/nxparser as a lenient quad stream parser (thank you @kaefer3000 et al. !), 

the following results were produced after running

```
preston history --anchor hash://sha256/f63892e3693f55911fb3bb564e7bb6ed78fb2d7ee34ff9aff5b5847d8d89f8c7 --remote https://linker.bio\
 | head
```

```
<hash://sha256/f63892e3693f55911fb3bb564e7bb6ed78fb2d7ee34ff9aff5b5847d8d89f8c7> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199> .
<hash://sha256/18b51a180c63929d5e3a50dbb72295579c2645546d22ae3fdcd5e2095c43d199> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697> .
Jan 31, 2023 1:15:12 PM org.semanticweb.yars.nx.parser.NxParser loadNext
WARNING: Moving on to the next line, as I couldn't parse line 114: 001/XMLSchema#dateTime> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .
org.semanticweb.yars.nx.parser.ParseException: Exception at position 0 while parsing: '001/XMLSchema#dateTime> <urn:uuid:8ae298b0-bf2a-4ce4-aa44-b41b0a0d0f6a> .'
	at org.semanticweb.yars.nx.parser.NxParser.parseNodesInternal(NxParser.java:264)
	at org.semanticweb.yars.nx.parser.NxParser.loadNext(NxParser.java:105)
	at org.semanticweb.yars.nx.parser.NxParser.next(NxParser.java:87)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:42)
	at bio.guoda.preston.store.ProvenanceTracerImpl.trace(ProvenanceTracerImpl.java:60)
	at bio.guoda.preston.cmd.CmdHistory.run(CmdHistory.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:92)
	at bio.guoda.preston.Preston.main(Preston.java:82)
<hash://sha256/8fdeacfb91b7fbe37e467234187e0bdf97fbacba2f7cee59896e8b8ef3714697> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/709f15825e694b7eb787b9d6c5bd9fb3f0fda92c6486666fa7a98b62b401a305> .
<hash://sha256/709f15825e694b7eb787b9d6c5bd9fb3f0fda92c6486666fa7a98b62b401a305> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/bdba58a35f5ff397a11c757ae0f0db07e59c4789c4e0d86e38bcfe61fdc74ad0> .
<hash://sha256/bdba58a35f5ff397a11c757ae0f0db07e59c4789c4e0d86e38bcfe61fdc74ad0> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/f4f762d1cfcabc01ece1643a3d8a0ce2c3d8f78db8da00bc9ecd5f631da0c5cc> .
<hash://sha256/f4f762d1cfcabc01ece1643a3d8a0ce2c3d8f78db8da00bc9ecd5f631da0c5cc> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/55553cd7d0142c8f277bd7300684d6a819a914f65b351e52a257ed2c841f5919> .
<hash://sha256/55553cd7d0142c8f277bd7300684d6a819a914f65b351e52a257ed2c841f5919> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/69da436fd0f564c5a621b2ec7970b780bb497526e158114510425ea25e1e093e> .
<hash://sha256/69da436fd0f564c5a621b2ec7970b780bb497526e158114510425ea25e1e093e> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/756c032afdd13afb3c69251557180f44651a189c76fc01a867a3b8ca8204499c> .
<hash://sha256/756c032afdd13afb3c69251557180f44651a189c76fc01a867a3b8ca8204499c> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/f2f14ce415515dc5bc3def57acd6360e628f9ff437540674bb81512988483b50> .
<hash://sha256/f2f14ce415515dc5bc3def57acd6360e628f9ff437540674bb81512988483b50> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/c844e6c783ccf954748efe116d2110cae0b6b30caea79821bb31a033da1e715d> .
```

So, instead of prematurely stopping to parse, the malformed line is skipped and parsing continues. 

Yay!
