### ISSUE TITLE
make tracking seeds explicit, instead of defaulting to seeds when no seeds nor explicit tracking locations are provided

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#225]
Currently,

```
preston track
```

will defaults to

```
preston track --seed https://idigbio.org,https://gbif.org,http://biocase.org 
```

and attempt to start tracking all of idigbio, gbif, and biocase.

Suggest to remove this default, and enable piping of statements into the track commands. 

e.g., 

```
preston ls | preston track 
```

This way, processors can re-examine previously tracked contents and re-associate their content.

**Comment by jhpoelen** [comment]
with this suggestion, 

```preston track```

would behave similarly to 

```preston cat```

'cause 

```preston ls | preston cat``` will cat all related content as provided by ```preston ls```

**Comment by jhpoelen** [comment]
Note that ```preston track``` without arguments now throws exception:

```
$ preston track 
java.lang.IllegalArgumentException: nothing to do: no tracked location or seed provided
	at bio.guoda.preston.cmd.CmdUpdate.initQueue(CmdUpdate.java:49)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:102)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:74)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:82)
	at bio.guoda.preston.Preston.main(Preston.java:72)
```

instead of waiting for input.
