### ISSUE TITLE
https://linker.bio/line:zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2 fails to resolve

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#227]
[`https://linker.bio/line:zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2`](https://linker.bio/line:zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2)

fails with error:

```
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]</h2>

URI: | /zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2
-- | --
500
java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
bio.guoda.preston.server.ContentServlet-4b9e255
java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
java.io.IOException: failed to find content identified by [<zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2>]

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:47)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:39)
	at bio.guoda.preston.server.ContentServlet.doGet(ContentServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.cmd.ContentQueryUtil.getContent(ContentQueryUtil.java:56)
	at bio.guoda.preston.cmd.ContentQueryUtil.copyContent(ContentQueryUtil.java:35)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:67)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:44)
	... 26 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:84)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:42)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:17)
	at bio.guoda.preston.cmd.ContentQueryUtil.getContent(ContentQueryUtil.java:48)
	... 29 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:82)
	... 32 more
Caused by: java.io.IOException: failed to find content identified by [&lt;zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2&gt;]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:70)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 34 more
</pre><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://eclipse.org/jetty" style="font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Powered by Jetty:// 9.4.43.v20210629</a><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
URI:	/zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2
STATUS:	500
MESSAGE:	java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
SERVLET:	bio.guoda.preston.server.ContentServlet-4b9e255
CAUSED BY:	java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
CAUSED BY:	java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
CAUSED BY:	bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
CAUSED BY:	bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
CAUSED BY:	java.io.IOException: failed to find content identified by [<zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2>]
Caused by:
java.lang.RuntimeException: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:47)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:39)
	at bio.guoda.preston.server.ContentServlet.doGet(ContentServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: problem retrieving [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.cmd.ContentQueryUtil.getContent(ContentQueryUtil.java:56)
	at bio.guoda.preston.cmd.ContentQueryUtil.copyContent(ContentQueryUtil.java:35)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:67)
	at bio.guoda.preston.cmd.CmdGet.run(CmdGet.java:44)
	... 26 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:84)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:42)
	at bio.guoda.preston.store.AliasDereferencer.get(AliasDereferencer.java:17)
	at bio.guoda.preston.cmd.ContentQueryUtil.getContent(ContentQueryUtil.java:48)
	... 29 more
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at bio.guoda.preston.store.AliasDereferencer.dereferenceAliasedHash(AliasDereferencer.java:82)
	... 32 more
Caused by: java.io.IOException: failed to find content identified by [<zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:70)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 34 more
[Powered by Jetty:// 9.4.43.v20210629](https://eclipse.org/jetty)
```

**Comment by jhpoelen** [comment]
Note however that after starting a local preston server using

`preston s --remote https://linker.bio`

```
curl 'http://localhost:8080/line:zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2'
```

yielded:

```
id	modified	language	institutionID	collectionID	institutionCode	collectionCode	ownerInstitutionCode	basisOfRecord	occurrenceID	catalogNumber	occurrenceRemarks	recordNumber	recordedBy	individualCount	sex	lifeStage	preparations	disposition	otherCatalogNumbers	associatedTaxa	samplingProtocol	eventDate	startDayOfYear	endDayOfYear	year	month	day	verbatimEventDate	habitat	fieldNumber	fieldNotes	waterBody	country	stateProvince	county	municipality	locality	verbatimElevation	minimumElevationInMeters	maximumElevationInMeters	verbatimDepth	minimumDepthInMeters	maximumDepthInMeters	locationRemarks	verbatimCoordinates	decimalLatitude	decimalLongitude	geodeticDatum	coordinateUncertaintyInMeters	footprintWKT	georeferencedBy	georeferenceProtocol	georeferenceSources	georeferenceVerificationStatus	georeferenceRemarks	identifiedBy	dateIdentified	identificationReferences	identificationRemarks	identificationQualifier	typeStatus	scientificName	family	genus	specificEpithet	infraspecificEpithet	taxonRank	scientificNameAuthorship	taxonRemarks
urn:catalog:CAS:TYPE:19059	2022-09-30 14:17:20	en	http://grbio.org/institution/california-academy-sciences	http://grscicoll.org/institutional-collection/entomology-types	CASC	CASTYPE	CASC	PreservedSpecimen	urn:catalog:CAS:TYPE:19059	CASTYPE19059	Cornell University Expedition; Nunenmacher Collection.		R. G. Harris	1	male	adult	pinned	permanent deposit				1919-11-07	311	312	1919	11	7	7-8 Nov-'19					Brazil	Minas Gerais			Cordisburgo																			Robert D. Gordon & Claudio Canepari		Gordon, Robert D., Claudio Canepari & Guy A. Hanley. 2014. South American Coccinellidae (Coleoptera), Part XVI: systematic revision of Brachiacantha Dejean (Coccinellinae: Hyperaspidini). Insecta Mundi [New Series] 0390: 1-76. [17]	Authority for currently accepted name: Gordon, Robert D., Claudio Canepari & Guy A. Hanley. 2014. South American Coccinellidae (Coleoptera), Part XVI: systematic revision of Brachiacantha Dejean (Coccinellinae: Hyperaspidini). Insecta Mundi [New Series] 0390: 1-76. [17]	Coccinellinae	holotype	Brachiacantha pauline Gordon & Canepari in Gordon, Canepari & Hanley, 2014	Coccinellidae					Gordon & Canepari in Gordon, Canepari & Hanley, 2014	Currently accepted name: Brachiacantha pauline Gordon & Canepari in Gordon, Canepari & Hanley, 2014
```

**Comment by jhpoelen** [comment]
root was was a nginx rewrite rule and was apparently fixed in https://github.com/bio-guoda/preston-service/commit/280df725e96ee0284d4157da82c0790ca1826d0d . 

now,

```
curl 'https://linker.bio/line:zip:hash://sha256/110f398aa4c8a4be870c7b3c1d698c32eb2c8dad878b614fe8e8f7a153251a43!/occurrence.txt!/L1-L2'
```

returns:

```
id	modified	language	institutionID	collectionID	institutionCode	collectionCode	ownerInstitutionCode	basisOfRecord	occurrenceID	catalogNumber	occurrenceRemarks	recordNumber	recordedBy	individualCount	sex	lifeStage	preparations	disposition	otherCatalogNumbers	associatedTaxa	samplingProtocol	eventDate	startDayOfYear	endDayOfYear	year	month	day	verbatimEventDate	habitat	fieldNumber	fieldNotes	waterBody	country	stateProvince	county	municipality	locality	verbatimElevation	minimumElevationInMeters	maximumElevationInMeters	verbatimDepth	minimumDepthInMeters	maximumDepthInMeters	locationRemarks	verbatimCoordinates	decimalLatitude	decimalLongitude	geodeticDatum	coordinateUncertaintyInMeters	footprintWKT	georeferencedBy	georeferenceProtocol	georeferenceSources	georeferenceVerificationStatus	georeferenceRemarks	identifiedBy	dateIdentified	identificationReferences	identificationRemarks	identificationQualifier	typeStatus	scientificName	family	genus	specificEpithet	infraspecificEpithet	taxonRank	scientificNameAuthorship	taxonRemarks
urn:catalog:CAS:TYPE:19059	2022-09-30 14:17:20	en	http://grbio.org/institution/california-academy-sciences	http://grscicoll.org/institutional-collection/entomology-types	CASC	CASTYPE	CASC	PreservedSpecimen	urn:catalog:CAS:TYPE:19059	CASTYPE19059	Cornell University Expedition; Nunenmacher Collection.		R. G. Harris	1	male	adult	pinned	permanent deposit				1919-11-07	311	312	1919	11	7	7-8 Nov-'19					Brazil	Minas Gerais			Cordisburgo																			Robert D. Gordon & Claudio Canepari		Gordon, Robert D., Claudio Canepari & Guy A. Hanley. 2014. South American Coccinellidae (Coleoptera), Part XVI: systematic revision of Brachiacantha Dejean (Coccinellinae: Hyperaspidini). Insecta Mundi [New Series] 0390: 1-76. [17]	Authority for currently accepted name: Gordon, Robert D., Claudio Canepari & Guy A. Hanley. 2014. South American Coccinellidae (Coleoptera), Part XVI: systematic revision of Brachiacantha Dejean (Coccinellinae: Hyperaspidini). Insecta Mundi [New Series] 0390: 1-76. [17]	Coccinellinae	holotype	Brachiacantha pauline Gordon & Canepari in Gordon, Canepari & Hanley, 2014	Coccinellidae					Gordon & Canepari in Gordon, Canepari & Hanley, 2014	Currently accepted name: Brachiacantha pauline Gordon & Canepari in Gordon, Canepari & Hanley, 2014
```
