### ISSUE TITLE
preston cat does not resolve content when anchored to specific provenance log hash

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#252]
```
preston cat\
 --remote https://zenodo.org/record/8124478/files\
 https://github.com/globalbioticinteractions/globi-taxon-names/raw/main/taxon-name-mapping.csv\
 | head -n2
```

produces:

```
< 1 mm organic debric,organic material,functional name,provided by Brian Hayden
< 1 mm organic debris,organic material,functional name,provided by Brian Hayden
```

however 

```
preston cat\
 --remote https://zenodo.org/record/8124478/files\
 --anchor hash://sha256/0e9bc57bc082b58a2c7a509bb73362b258ec8ddfc6664898e25c639786413fda\
 https://github.com/globalbioticinteractions/globi-taxon-names/raw/main/taxon-name-mapping.csv\
 | head -n2
```

produces:

```
[main] WARN bio.guoda.preston.cmd.ReplayUtil - No provenance found. Please use/create a Preston data archive.
java.io.IOException: problem retrieving [https://github.com/globalbioticinteractions/globi-taxon-names/raw/main/taxon-name-mapping.csv]
	at bio.guoda.preston.cmd.ContentQueryUtil.getContent(ContentQueryUtil.java:58)
	at bio.guoda.preston.cmd.ContentQueryUtil.copyContent(ContentQueryUtil.java:32)
```

expected that aliases be resolved within the scope of defined provenance anchor.

**Comment by jhpoelen** [comment]
After provided fixes, the following results are obtained:

```
$ preston cat --remote https://zenodo.org/record/8125362/files https://github.com/globalbioticinteractions/globi-taxon-names/raw/main/taxon-name-mapping.csv | head -n2
< 1 mm organic debric,organic material,functional name,provided by Brian Hayden
< 1 mm organic debris,organic material,functional name,provided by Brian Hayden
```


as well as


```
 preston cat --remote https://zenodo.org/record/8125362/files --anchor hash://sha256/0e9bc57bc082b58a2c7a509bb73362b258ec8ddfc6664898e25c639786413fda https://github.com/globalbioticinteractions/globi-taxon-names/raw/main/taxon-name-mapping.csv | head -n2
< 1 mm organic debric,organic material,functional name,provided by Brian Hayden
< 1 mm organic debris,organic material,functional name,provided by Brian Hayden
```
