### ISSUE TITLE
retrieve restricted content from Zenodo with proper credentials

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#314]
Zenodo offer a way to publish restricted content, where the metadata is public, but the content is restricted.

Currently, Preston supports Zenodo as a remote. However, even when a valid ZENODO_TOKEN is available, restricted content cannot be retrieved by their hash. 

e.g., 

```
ZENODO_TOKEN=[your token]\
 preston cat\
 --remote https://zenodo.org\
 hash://md5/587f269cfa00aa40b7b50243ea8bdab9 
```

does not yield any content, instead the following error message is shown:

```
Caused by: java.io.IOException: cannot find content identified by [<hash://md5/587f269cfa00aa40b7b50243ea8bdab9>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:75)
	at bio.guoda.preston.stream.ContentHashDereferencer.get(ContentHashDereferencer.java:24)
	... 20 more
```

Suggest to allow Preston to retrieve restricted content on Zenodo by their md5 as long as a valid ZENODO_TOKEN is present.

**Comment by jhpoelen** [comment]
Root cause of this issue is that Zenodo's search by md5 hashes does not appear to support credentials - and excludes hashes of restricted content.

However, you can work around Zenodo search index limitation by publishing content signatures (e.g., hash://md5/587f269cfa00aa40b7b50243ea8bdab9) as metadata in the Zenodo record. 

Now, you can get the hit for the restricted record (the metadata is openly available), and use access controlled download links to retrieve the content.

This approach was applied for https://batlit.org , https://taxodros.github.io etc.

**Comment by jhpoelen** [comment]
Example search for "hash://md5/587f269cfa00aa40b7b50243ea8bdab9" shown below points to restricted record (at time of writing 2024-12-16).

![image](https://github.com/user-attachments/assets/4f58be5e-11b1-4d29-a771-8b4eb2149e45)

**Comment by jhpoelen** [comment]
The desired functionality is now available, e.g.,

```
ZENODO_TOKEN=[some token] preston cat --remote https://zenodo.org --no-progress hash://md5/587f269cfa00aa40b7b50243ea8bdab9 | md5sum
```

produces the expected

```
587f269cfa00aa40b7b50243ea8bdab9
```

only if the ZENODO_TOKEN is associated with an account with access to the restricted file.

**Comment by jhpoelen** [comment]
fyi @cboettig
