### ISSUE TITLE
unexpected exception when calculating tika + tlsh on  hash://sha256/b76bd013d48dcdebe9d225b8a88a42b16498e6a67d3334734978cfecf45c26e7 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#61]
$ preston cat hash://sha256/b76bd013d48dcdebe9d225b8a88a42b16498e6a67d3334734978cfecf45c26e7 | ./preston.jar hash -a tika
May 08, 2020 6:07:15 PM bio.guoda.preston.cmd.CmdLine run
SEVERE: unexpected exception
java.lang.ArrayIndexOutOfBoundsException: -3
	at com.trendmicro.tlsh.TlshCreator.update(TlshCreator.java:180)
	at bio.guoda.preston.HashGeneratorTLSHTika$TLSHInputStream.read(HashGeneratorTLSHTika.java:90)
	at bio.guoda.preston.HashGeneratorTLSHTika$TLSHInputStream.read(HashGeneratorTLSHTika.java:83)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
	at bio.guoda.preston.HashGeneratorTLSHTika.calculateLTSH(HashGeneratorTLSHTika.java:53)
	at bio.guoda.preston.HashGeneratorTLSHTika.hash(HashGeneratorTLSHTika.java:32)
	at bio.guoda.preston.HashGeneratorTLSHTika.hash(HashGeneratorTLSHTika.java:21)
	at bio.guoda.preston.HashGeneratorAbstract.hash(HashGeneratorAbstract.java:19)
	at bio.guoda.preston.HashGeneratorAbstract.hash(HashGeneratorAbstract.java:14)
	at bio.guoda.preston.cmd.CmdHash.run(CmdHash.java:41)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)

**Comment by jhpoelen** [comment]
note that calculating the tlsh hash works just fine:
```
$ preston cat hash://sha256/b76bd013d48dcdebe9d225b8a88a42b16498e6a67d3334734978cfecf45c26e7 | ./preston.jar hash -a tlsh
hash://tlsh/8336b78098f5f8d642efa0bd655d23a432a0b915da9b4e4178e643033ed00fd17eb
```
'

**Comment by jhpoelen** [comment]
I was able to reproduce the issue independently of tika, so it appears to be a tlsh computation issue.
```
$ java -jar tika-app-1.24.1.jar -t file://$PWD/input/big.zip | pv -l | gzip > output/big.txt.gz
$ zcat output/big.txt.gz | ./preston.jar hash -a tlsh
May 08, 2020 6:35:00 PM bio.guoda.preston.cmd.CmdLine run
SEVERE: unexpected exception
java.lang.ArrayIndexOutOfBoundsException: -3
	at com.trendmicro.tlsh.TlshCreator.update(TlshCreator.java:180)
	at bio.guoda.preston.HashGeneratorTLSHashIRI$TLSHInputStream.read(HashGeneratorTLSHashIRI.java:64)
	at bio.guoda.preston.HashGeneratorTLSHashIRI$TLSHInputStream.read(HashGeneratorTLSHashIRI.java:57)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
	at bio.guoda.preston.HashGeneratorTLSHashIRI.calculateLTSH(HashGeneratorTLSHashIRI.java:27)
	at bio.guoda.preston.HashGeneratorTLSHashIRI.hash(HashGeneratorTLSHashIRI.java:18)
	at bio.guoda.preston.HashGeneratorTLSHashIRI.hash(HashGeneratorTLSHashIRI.java:14)
	at bio.guoda.preston.HashGeneratorAbstract.hash(HashGeneratorAbstract.java:19)
	at bio.guoda.preston.HashGeneratorAbstract.hash(HashGeneratorAbstract.java:14)
	at bio.guoda.preston.cmd.CmdHash.run(CmdHash.java:41)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
```

**Comment by jhpoelen** [comment]
Root cause of the unexpected ArrayIndexOutOfBoundsException was a length variable of type int that overflowed with long files.

**Comment by jhpoelen** [comment]
https://github.com/bio-guoda/preston/blob/a29beecb3abf36a0825a12c90a84a118593b505c/src/main/java/com/trendmicro/tlsh/TlshCreator.java#L98

with root cause fixed at 
https://github.com/bio-guoda/preston/blob/a29beecb3abf36a0825a12c90a84a118593b505c/src/main/java/com/trendmicro/tlsh/TlshCreator.java#L171
