### ISSUE TITLE
ArrayIndexOutOfBoundsException on running "preston match"

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#81]
to reproduce:

```
git clone https://github.com/bio-guoda/preston-amazon 
cd preston-amazon
preston ls | preston match 
```

expected results: 
matches are logged as nquads.

actual results:
some results are logged, but a ArrayIndexOutOfBoundsException is thrown:

```
<hash://sha256/052c70c60e7c17123a1bdf18d2ce607cee1b0d96157b6174aae08a2f2f8d53d8> <http://www.w3.org/ns/prov#hadMember> <58414378-4fb2-47e0-8dd5-8b55d5c77117> .
<58414378-4fb2-47e0-8dd5-8b55d5c77117> <http://www.w3.org/ns/prov#hadMember> <http://data.freshwaterbiodiversity.eu/ipt/archive.do?r=bfe_105> .
<http://data.freshwaterbiodiversity.eu/ipt/archive.do?r=bfe_105> <http://purl.org/dc/elements/1.1/format> "application/dwca" .
<hash://sha256/97cbeae429fbc95d1859f7afa28b33f08ac64125ba72511c49c4b77ca66d2d66> <http://www.w3.org/ns/prov#generatedAtTime> "2018-09-05T08:34:39.513Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<hash://sha256/97cbeae429fbc95d1859f7afa28b33f08ac64125ba72511c49c4b77ca66d2d66> <http://www.w3.org/ns/prov#wasGeneratedBy> <a12738d5-22d3-4e2d-9e98-e8daab4c42bc> .
Sep 23, 2020 8:21:53 AM bio.guoda.preston.cmd.CmdLine run
SEVERE: unexpected exception
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at bio.guoda.preston.process.TextMatcher.parseAsText(TextMatcher.java:163)
```

See attached log.
[match.log](https://github.com/bio-guoda/preston/files/5270533/match.log)

**Comment by mielliott** [comment]
Preston's text matcher wasn't updating the current byte index correctly when the input stream didn't have any matches. It's fixed now, but the `preston match` is having another array bounds exception when parsing `hash://sha256/4256fd83db9270d2236776bc4bd45e22b15235e0798ba59952f8ddd1f7fbe7b2` from preston-amazon. Working on a fix.

**Comment by mielliott** [comment]
The default `charset` `decode` function was replacing uninterpretable byte sequences with "unknown" characters. I changed the decoder to ignore those bytes instead, and account for any resulting change in character byte positions.

I ran `preston match` successfully on preston-amazon and found 45,451 URLs.

```
$ git clone https://github.com/bio-guoda/preston-amazon 
$ cd preston-amazon
$ time preston ls | preston match > urls
real    0m3.264s
user    0m4.813s
sys     0m1.453s
$ wc -l urls
45451
$ tail urls
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8409-8451> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8814-8856> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8863-8905> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9164-9206> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9569-9611> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9618-9660> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9919-9961> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10324-10366> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10373-10415> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10674-10716> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <77ed1e55-8d40-4b89-9a91-f1f8c92822b6> .
```

And just to get that warm fuzzy and feeling of seeing it work:
```
$ preston get hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062 > 94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062
$ unzip -p 94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062 references.txt | cut -z -b10674-10716
http://dx.doi.org/10.3897/zookeys.740.14640
```

Sadly, I couldn't figure out how to shorten it to one line instead of two. I hoped something like `preston get hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062 | unzip -p - references.txt | cut -z -b10674-10716` would work... but no luck (and no error messages, for that matter).

@jhpoelen the issue should be fixed now. Can you confirm and close?

**Comment by jhpoelen** [comment]
Nice! Thank for making me feel warm and fuzzy! I was able to reproduce your results:

```shell
$ git clone https://github.com/bio-guoda/preston-amazon
$ cd preston-amazon
$ time preston ls | preston match > urls
real	0m6.443s
user	0m10.653s
sys	0m1.747s
$ wc -l urls
45451 urls
$ tail urls
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8409-8451> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8814-8856> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b8863-8905> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9164-9206> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9569-9611> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9618-9660> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b9919-9961> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10324-10366> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10373-10415> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
<cut:zip:hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062!/references.txt!/b10674-10716> <http://www.w3.org/ns/prov#value> "http://dx.doi.org/10.3897/zookeys.740.14640" <9d59e57a-1dca-447f-9c48-c843b7ae2381> .
$ preston get hash://sha256/94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062 > 94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062
$ unzip -p 94a4fc4824d951c0155860e3e5c4c662afcfae55d52a25105bca1cb6a7b3a062 references.txt | cut -z -b10674-10716
http://dx.doi.org/10.3897/zookeys.740.14640
```

Thanks for providing a first pass at a reliable method to point into datasets. I can't even start to imagine all the possible features this unlocks . . . but we can start with linking Arctos host-parasite specimen ids across dwca archives.
