### ISSUE TITLE
OutOfMemoryException on finding urls in hash://sha256/022661ff64d57492be767623b87174f46354b6665abbbf962512ebb1519031bd

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#83]
Steps to reproduce:

```shell
$ preston track "http://apm-ipt.br.fgov.be:8080/ipt/archive.do?r=botanical_collection" | preston match 
```
expected:
provenance log with url references is generated

actual:
CPU goes to ~400% (on four core machine) and the following exception is produced:

```
<61523152-878d-4cfa-a3c6-49b3184fb948> <http://www.w3.org/ns/prov#wasInformedBy> <38f2a794-3338-4125-a418-87db235026c8> <61523152-878d-4cfa-a3c6-49b3184fb948> .
<61523152-878d-4cfa-a3c6-49b3184fb948> <http://www.w3.org/ns/prov#used> <http://apm-ipt.br.fgov.be:8080/ipt/archive.do?r=botanical_collection> <61523152-878d-4cfa-a3c6-49b3184fb948> .
Sep 28, 2020 2:51:42 PM bio.guoda.preston.cmd.CmdLine run
SEVERE: unexpected exception
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:795)
	at java.nio.charset.Charset.encode(Charset.java:843)
	at bio.guoda.preston.process.TextMatcher.parseAsText(TextMatcher.java:193)
	at bio.guoda.preston.process.TextMatcher.attemptToParseAsText(TextMatcher.java:134)
	at bio.guoda.preston.process.TextMatcher.attemptToParse(TextMatcher.java:92)
	at bio.guoda.preston.process.TextMatcher.parseAsArchive(TextMatcher.java:146)
	at bio.guoda.preston.process.TextMatcher.attemptToParseAsArchive(TextMatcher.java:98)
	at bio.guoda.preston.process.TextMatcher.attemptToParse(TextMatcher.java:90)
	at bio.guoda.preston.process.TextMatcher.on(TextMatcher.java:74)
	at bio.guoda.preston.process.StatementsListenerEmitterAdapter.on(StatementsListenerEmitterAdapter.java:12)
	at bio.guoda.preston.cmd.CmdProcess.handleNonBlankMessages(CmdProcess.java:76)
	at bio.guoda.preston.cmd.CmdProcess.access$000(CmdProcess.java:28)
	at bio.guoda.preston.cmd.CmdProcess$1.emit(CmdProcess.java:52)
	at bio.guoda.preston.cmd.CmdProcess$1.emit(CmdProcess.java:47)
	at bio.guoda.preston.process.EmittingStreamRDF.copyOnEmit(EmittingStreamRDF.java:51)
	at bio.guoda.preston.process.EmittingStreamRDF.parseAndEmit(EmittingStreamRDF.java:40)
	at bio.guoda.preston.cmd.CmdProcess.processQueue(CmdProcess.java:57)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:125)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:78)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:19)
```

**Comment by jhpoelen** [comment]
Root cause is likely https://github.com/bio-guoda/preston/blob/8a44764fc80b732f831701e0451d7e25b5edca58/src/main/java/bio/guoda/preston/process/TextMatcher.java#L69 . Statement are cached in memory to be submitted in one big batch as a new activity. Sounds like we need some batching mechanism.

**Comment by jhpoelen** [comment]
@mielliott I took a stab as solving this issue by introducing batching of statements in the TextMatcher. I also removed the functionality to let the CmdMatcher automatically append to the provenance log. If output of the matcher is to be added to the provenance log, the output of ```preston match``` can be piping into ```preston process``` . 

After these changes, I was able to run:

```
$ preston cat "hash://sha256/022661ff64d57492be767623b87174f46354b6665abbbf962512ebb1519031bd" --remote https://deeplinker.org > /dev/null
$ time echo "<https://example.org> <http://purl.org/pav/hasVersion> <hash://sha256/022661ff64d57492be767623b87174f46354b6665abbbf962512ebb1519031bd> ." | preston match | pv -l | wc -l
14.2M 0:05:14 [45.3k/s] [                             <=>                                                                             ]
14229035

real 5m14.191s
user 5m51.775s
sys 1m52.327s
```

to extract about 14.2M urls from a 100MB zip file ~ 1.5GB uncompressed.

Please review.

**Comment by mielliott** [comment]
Thanks for taking care of this @jhpoelen . Looks like a good solution. I reviewed the code and am closing the issue.
